using System.Net;
using System.Reflection;
using Sendly.Exceptions;
using Sendly.Models;
using Sendly.Tests.Fixtures;
using Xunit;

namespace Sendly.Tests;

/// <summary>
/// Tests for automatic idempotency keys - generation, retry reuse, rotation.
/// </summary>
public class IdempotencyTests : IDisposable
{
    private const string AutoKeyPattern =
        @"^sendly-dotnet-retry-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$";

    private const string MessageJson = @"{
        ""id"": ""msg_123"",
        ""to"": ""+15551234567"",
        ""text"": ""Hello World"",
        ""status"": ""queued"",
        ""credits_used"": 1,
        ""created_at"": ""2024-01-20T10:00:00Z"",
        ""updated_at"": ""2024-01-20T10:00:00Z""
    }";

    private const string BatchJson = @"{
        ""batchId"": ""batch_123"",
        ""status"": ""completed"",
        ""total"": 1,
        ""sent"": 1,
        ""failed"": 0,
        ""optedOutSkipped"": 0,
        ""invalidSkipped"": 0,
        ""creditsUsed"": 1,
        ""creditsRefunded"": 0,
        ""messages"": []
    }";

    private readonly MockHttpMessageHandler _mockHandler;
    private readonly HttpClient _httpClient;
    private readonly SendlyClient _client;

    public IdempotencyTests()
    {
        _mockHandler = new MockHttpMessageHandler();
        _httpClient = new HttpClient(_mockHandler)
        {
            BaseAddress = new Uri("https://api.test.com")
        };

        // Use reflection to inject the mock HttpClient
        _client = new SendlyClient("test_api_key");
        var httpClientField = typeof(SendlyClient).GetField("_httpClient", BindingFlags.NonPublic | BindingFlags.Instance);
        httpClientField?.SetValue(_client, _httpClient);
    }

    public void Dispose()
    {
        _client?.Dispose();
        _httpClient?.Dispose();
        _mockHandler?.Dispose();
    }

    private string? KeyOfRequest(int index)
    {
        var request = _mockHandler.Requests[index];
        return request.Headers.TryGetValues("Idempotency-Key", out var values)
            ? values.FirstOrDefault()
            : null;
    }

    #region Automatic Key Generation Tests

    [Fact]
    public async Task SendAsync_Post_AttachesAutoGeneratedKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync("+15551234567", "Hello!");

        // Assert
        var key = KeyOfRequest(0);
        Assert.NotNull(key);
        Assert.Matches(AutoKeyPattern, key);
        Assert.True(key!.Length <= 255);
    }

    [Fact]
    public async Task ListAsync_Get_DoesNotAttachKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(@"{""data"": [], ""has_more"": false, ""total"": 0}");

        // Act
        await _client.Messages.ListAsync(new ListMessagesOptions { Limit = 10 });

        // Assert
        Assert.Null(KeyOfRequest(0));
    }

    [Fact]
    public async Task CancelScheduledAsync_Delete_DoesNotAttachKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(
            @"{""id"": ""schd_x"", ""status"": ""cancelled"", ""credits_refunded"": 1}");

        // Act
        await _client.Messages.CancelScheduledAsync("schd_x");

        // Assert
        Assert.Null(KeyOfRequest(0));
    }

    [Fact]
    public async Task SendBatchAsync_DoesNotAutoAttachKey()
    {
        // Arrange - the batch endpoint dedupes header-less retries by content
        _mockHandler.QueueSuccessResponse(BatchJson);

        var request = new SendBatchRequest
        {
            Messages = new List<BatchMessageItem>
            {
                new BatchMessageItem("+15551234567", "Hi!")
            }
        };

        // Act
        await _client.Messages.SendBatchAsync(request);

        // Assert
        Assert.Null(KeyOfRequest(0));
    }

    [Fact]
    public async Task UploadAsync_Media_AttachesAutoGeneratedKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(
            @"{""data"": {""id"": ""med_x"", ""url"": ""https://cdn.example.com/x.jpg""}}");

        using var stream = new MemoryStream(new byte[] { 1, 2, 3 });

        // Act
        await _client.Media.UploadAsync(stream, "x.jpg", "image/jpeg");

        // Assert
        var key = KeyOfRequest(0);
        Assert.NotNull(key);
        Assert.Matches(AutoKeyPattern, key);
    }

    [Fact]
    public async Task SendAsync_TwoLogicalRequests_UseDistinctKeys()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(MessageJson);
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync("+15551234567", "First");
        await _client.Messages.SendAsync("+15551234567", "Second");

        // Assert
        var first = KeyOfRequest(0);
        var second = KeyOfRequest(1);
        Assert.NotNull(first);
        Assert.NotNull(second);
        Assert.NotEqual(first, second);
    }

    #endregion

    #region Retry Behavior Tests

    [Fact]
    public async Task SendAsync_TimeoutRetry_ReusesKey()
    {
        // Arrange
        _mockHandler.QueueException(new TaskCanceledException("The request was canceled"));
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        var message = await _client.Messages.SendAsync("+15551234567", "Hello!");

        // Assert
        Assert.Equal("msg_123", message.Id);
        Assert.Equal(2, _mockHandler.Requests.Count);
        Assert.Equal(KeyOfRequest(0), KeyOfRequest(1));
    }

    [Fact]
    public async Task SendAsync_NetworkErrorRetry_ReusesKey()
    {
        // Arrange
        _mockHandler.QueueException(new HttpRequestException("Network request failed"));
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        var message = await _client.Messages.SendAsync("+15551234567", "Hello!");

        // Assert
        Assert.Equal("msg_123", message.Id);
        Assert.Equal(2, _mockHandler.Requests.Count);
        Assert.Equal(KeyOfRequest(0), KeyOfRequest(1));
    }

    [Fact]
    public async Task SendAsync_ServerErrorRetry_RotatesKey()
    {
        // Arrange
        _mockHandler.QueueResponse(HttpStatusCode.InternalServerError,
            @"{""error"": ""Server error""}");
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        var message = await _client.Messages.SendAsync("+15551234567", "Hello!");

        // Assert
        Assert.Equal("msg_123", message.Id);
        Assert.Equal(2, _mockHandler.Requests.Count);
        var first = KeyOfRequest(0);
        var second = KeyOfRequest(1);
        Assert.NotNull(first);
        Assert.NotNull(second);
        Assert.NotEqual(first, second);
    }

    [Fact]
    public async Task SendAsync_ServerErrorThenTimeout_KeepsRotatedKey()
    {
        // Arrange
        _mockHandler.QueueResponse(HttpStatusCode.InternalServerError,
            @"{""error"": ""Server error""}");
        _mockHandler.QueueException(new TaskCanceledException("The request was canceled"));
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        var message = await _client.Messages.SendAsync("+15551234567", "Hello!");

        // Assert
        Assert.Equal("msg_123", message.Id);
        Assert.Equal(3, _mockHandler.Requests.Count);
        var first = KeyOfRequest(0);
        var second = KeyOfRequest(1);
        var third = KeyOfRequest(2);
        Assert.NotEqual(first, second);
        Assert.Equal(second, third);
    }

    [Fact]
    public async Task SendAsync_NonServerErrorRetry_KeepsKey()
    {
        // Arrange
        _mockHandler.QueueResponse(HttpStatusCode.Conflict,
            @"{""error"": ""conflict"", ""message"": ""Resource busy""}");
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        var message = await _client.Messages.SendAsync("+15551234567", "Hello!");

        // Assert
        Assert.Equal("msg_123", message.Id);
        Assert.Equal(2, _mockHandler.Requests.Count);
        Assert.Equal(KeyOfRequest(0), KeyOfRequest(1));
    }

    [Fact]
    public async Task UploadAsync_ServerErrorRetry_RotatesKey()
    {
        // Arrange
        _mockHandler.QueueResponse(HttpStatusCode.BadGateway,
            @"{""error"": ""Server error""}");
        _mockHandler.QueueSuccessResponse(
            @"{""data"": {""id"": ""med_x"", ""url"": ""https://cdn.example.com/x.jpg""}}");

        using var stream = new MemoryStream(new byte[] { 1, 2, 3 });

        // Act
        await _client.Media.UploadAsync(stream, "x.jpg", "image/jpeg");

        // Assert
        Assert.Equal(2, _mockHandler.Requests.Count);
        var first = KeyOfRequest(0);
        var second = KeyOfRequest(1);
        Assert.Matches(AutoKeyPattern, first);
        Assert.Matches(AutoKeyPattern, second);
        Assert.NotEqual(first, second);
    }

    #endregion

    #region Caller-Supplied Key Tests

    [Fact]
    public async Task SendAsync_WithCallerKey_SendsKeyVerbatim()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync(
            new SendMessageRequest("+15551234567", "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "order-4821-shipped" });

        // Assert
        Assert.Equal("order-4821-shipped", KeyOfRequest(0));
    }

    [Fact]
    public async Task SendAsync_WithCallerKey_ServerErrorRetry_NeverRotates()
    {
        // Arrange
        _mockHandler.QueueResponse(HttpStatusCode.InternalServerError,
            @"{""error"": ""Server error""}");
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync(
            new SendMessageRequest("+15551234567", "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "order-4821-shipped" });

        // Assert
        Assert.Equal(2, _mockHandler.Requests.Count);
        Assert.Equal("order-4821-shipped", KeyOfRequest(0));
        Assert.Equal("order-4821-shipped", KeyOfRequest(1));
    }

    [Fact]
    public async Task SendAsync_WithCallerKey_TimeoutRetry_ReusesKey()
    {
        // Arrange
        _mockHandler.QueueException(new TaskCanceledException("The request was canceled"));
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync(
            new SendMessageRequest("+15551234567", "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "signup-otp-user-99" });

        // Assert
        Assert.Equal(2, _mockHandler.Requests.Count);
        Assert.Equal("signup-otp-user-99", KeyOfRequest(0));
        Assert.Equal("signup-otp-user-99", KeyOfRequest(1));
    }

    [Fact]
    public async Task SendBatchAsync_WithCallerKey_SendsKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(BatchJson);

        var request = new SendBatchRequest
        {
            Messages = new List<BatchMessageItem>
            {
                new BatchMessageItem("+15551234567", "Hi!")
            }
        };

        // Act
        await _client.Messages.SendBatchAsync(request,
            new IdempotentRequestOptions { IdempotencyKey = "campaign-77-wave-1" });

        // Assert
        Assert.Equal("campaign-77-wave-1", KeyOfRequest(0));
    }

    [Fact]
    public async Task ScheduleAsync_WithCallerKey_SendsKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(@"{
            ""id"": ""schd_x"",
            ""to"": ""+15551234567"",
            ""text"": ""Reminder!"",
            ""status"": ""scheduled"",
            ""scheduled_at"": ""2030-01-20T10:00:00Z"",
            ""created_at"": ""2024-01-20T10:00:00Z""
        }");

        // Act
        await _client.Messages.ScheduleAsync(
            new ScheduleMessageRequest("+15551234567", "Reminder!", "2030-01-20T10:00:00Z"),
            new IdempotentRequestOptions { IdempotencyKey = "reminder-visit-31" });

        // Assert
        Assert.Equal("reminder-visit-31", KeyOfRequest(0));
    }

    [Fact]
    public async Task SendAsync_WithEmptyCallerKey_FallsBackToAutoKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync(
            new SendMessageRequest("+15551234567", "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "" });

        // Assert
        var key = KeyOfRequest(0);
        Assert.NotNull(key);
        Assert.Matches(AutoKeyPattern, key);
    }

    [Fact]
    public async Task SendAsync_WithWhitespaceCallerKey_FallsBackToAutoKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(MessageJson);

        // Act
        await _client.Messages.SendAsync(
            new SendMessageRequest("+15551234567", "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "   " });

        // Assert
        var key = KeyOfRequest(0);
        Assert.NotNull(key);
        Assert.Matches(AutoKeyPattern, key);
    }

    [Fact]
    public async Task SendAsync_WithNonAsciiCallerKey_ThrowsValidationExceptionWithoutRequest()
    {
        // Act & Assert
        var exception = await Assert.ThrowsAsync<ValidationException>(
            () => _client.Messages.SendAsync(
                new SendMessageRequest("+15551234567", "Hello!"),
                new IdempotentRequestOptions { IdempotencyKey = "Заказ-42" }));

        Assert.Contains("Idempotency key must be 1-255 printable ASCII characters", exception.Message);
        Assert.Empty(_mockHandler.Requests);
    }

    [Fact]
    public async Task SendAsync_WithTooLongCallerKey_ThrowsValidationExceptionWithoutRequest()
    {
        // Act & Assert
        await Assert.ThrowsAsync<ValidationException>(
            () => _client.Messages.SendAsync(
                new SendMessageRequest("+15551234567", "Hello!"),
                new IdempotentRequestOptions { IdempotencyKey = new string('k', 256) }));

        Assert.Empty(_mockHandler.Requests);
    }

    [Fact]
    public async Task SendAsync_WhatsApp_WithCallerKey_SendsKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(@"{
            ""id"": ""msg_wa"",
            ""channel"": ""whatsapp"",
            ""to"": ""+15551234567"",
            ""from"": ""+15559876543"",
            ""status"": ""queued"",
            ""whatsapp"": {""kind"": ""text""}
        }");

        // Act
        await _client.Messages.SendAsync(
            new SendWhatsAppMessageRequest("+15551234567", "+15559876543", text: "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "wa-hello-1" });

        // Assert
        Assert.Equal("wa-hello-1", KeyOfRequest(0));
    }

    [Fact]
    public async Task SendAsync_Rcs_WithCallerKey_SendsKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(@"{
            ""id"": ""msg_rcs"",
            ""channel"": ""rcs"",
            ""to"": ""+15551234567"",
            ""status"": ""queued"",
            ""rcs"": {""kind"": ""text""}
        }");

        // Act
        await _client.Messages.SendAsync(
            new SendRcsMessageRequest("+15551234567", text: "Hello!"),
            new IdempotentRequestOptions { IdempotencyKey = "rcs-hello-1" });

        // Assert
        Assert.Equal("rcs-hello-1", KeyOfRequest(0));
    }

    [Fact]
    public async Task SendGroupAsync_WithCallerKey_SendsKey()
    {
        // Arrange
        _mockHandler.QueueSuccessResponse(@"{
            ""id"": ""msg_x"",
            ""group_message_id"": ""grp_x"",
            ""status"": ""queued""
        }");

        // Act
        await _client.Messages.SendGroupAsync(
            new SendGroupMessageRequest
            {
                To = new List<string> { "+14155551234", "+14155555678" },
                Text = "Team sync at noon"
            },
            new IdempotentRequestOptions { IdempotencyKey = "standup-ping-0823" });

        // Assert
        Assert.Equal("standup-ping-0823", KeyOfRequest(0));
    }

    #endregion
}
